//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uchet.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class NormalTime
    {
        public int ID { get; set; }
        public int ID_Rabotnika { get; set; }
        public string Dolshost { get; set; }
        public string TimeMonth { get; set; }
    
        public virtual Rabotniki Rabotniki { get; set; }
    }
}
