//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uchet.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkTime
    {
        public int ID_Rabotnika { get; set; }
        public string den1 { get; set; }
        public string den2 { get; set; }
        public string den3 { get; set; }
        public string den4 { get; set; }
        public string den5 { get; set; }
        public string den6 { get; set; }
        public string den7 { get; set; }
        public string den8 { get; set; }
        public string den9 { get; set; }
        public string den10 { get; set; }
        public string den11 { get; set; }
        public string den12 { get; set; }
        public string den13 { get; set; }
        public string den14 { get; set; }
        public string den15 { get; set; }
        public string den16 { get; set; }
        public string den17 { get; set; }
        public string den18 { get; set; }
        public string den19 { get; set; }
        public string den20 { get; set; }
        public string den21 { get; set; }
        public string den22 { get; set; }
        public string den23 { get; set; }
        public string den24 { get; set; }
        public string den25 { get; set; }
        public string den26 { get; set; }
        public string den27 { get; set; }
        public string den28 { get; set; }
        public string den29 { get; set; }
        public string den30 { get; set; }
        public string den31 { get; set; }
    
        public virtual Rabotniki Rabotniki { get; set; }
    }
}
